# Generated by Django 2.2.6 on 2019-11-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EditionChampionship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Championship')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Edition')),
            ],
            options={
                'verbose_name': 'EditionChampionship',
                'verbose_name_plural': 'EditionChampionships',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.AddField(
            model_name='championship',
            name='editions',
            field=models.ManyToManyField(through='app.EditionChampionship', to='app.Edition'),
        ),
    ]
