# Generated by Django 2.0 on 2019-11-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateField()),
                ('role', models.IntegerField(choices=[(0, 'Nacional'), (1, 'Internacional')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EditionChampionship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Championship')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Edition')),
            ],
            options={
                'verbose_name': 'EditionChampionship',
                'verbose_name_plural': 'EditionChampionships',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'People',
                'verbose_name_plural': 'Peoples',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('stadium', models.CharField(max_length=50, null=True)),
                ('foundation', models.CharField(max_length=50, null=True)),
                ('coach', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.People')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='participants',
            field=models.ManyToManyField(to='app.Team'),
        ),
        migrations.AddField(
            model_name='championship',
            name='editions',
            field=models.ManyToManyField(through='app.EditionChampionship', to='app.Edition'),
        ),
    ]
