# Generated by Django 2.2.6 on 2019-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
