# Generated by Django 2.2.7 on 2019-11-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brazilian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('score', models.IntegerField(null=True)),
                ('games', models.IntegerField(null=True)),
                ('wins', models.IntegerField(null=True)),
                ('draws', models.IntegerField(null=True)),
                ('loses', models.IntegerField(null=True)),
            ],
        ),
    ]
