# Generated by Django 2.2.6 on 2019-11-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191118_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='participants',
        ),
        migrations.AddField(
            model_name='edition',
            name='participants',
            field=models.ManyToManyField(to='app.Team'),
        ),
    ]
