# Generated by Django 2.2.6 on 2019-11-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191121_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='role',
            field=models.IntegerField(choices=[(0, 'Nacional'), (1, 'Internacional')], default=0),
        ),
        migrations.AddField(
            model_name='edition',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='championship',
            name='created',
            field=models.DateField(),
        ),
    ]
